### DISCUSSION TITLE
COP / ignoring spikes of

### DISCUSSION THREAD

**Discussion by kobius77** [mbuchber/ha_heliotherm#25] [Ideas]
this might only be an issue for air-source heatpumps, not sure if folks who contributed to this so far got any.

these models switch to defrosting mode about 10-20 minutes (probably dependant of outside temperature) after turning on - which briefly brings down the compressor to nearly zero, which results in a huge spike in the COP calculation as the compressor doesn't use electricity while there is still hot water flowing.

![image](https://github.com/mbuchber/ha_heliotherm/assets/3143680/2a94c6eb-3844-478f-9e86-d5bc8cc5bb26)

obviously this makes the history graph for COP rather useless. (yes, the timestamp of the beginning of "Abtaubetrieb" is the same as the spike)

![image](https://github.com/mbuchber/ha_heliotherm/assets/3143680/451c5976-d72b-491c-9e55-20e6b4528bc2)

till now i worked with modbus-sensors and smoothed out the spike in the one graph i have on the dashboard, but with this integration it might make sense to do it in code for less experienced users.

opinions?

**Comment by karussell** [comment]
What I did was defining a new sensor in the configuration.yaml and only if cop is withing 0 and 10 it is "available":

```yaml
template:
  - sensor:
      - name: "COP with availability"
        unique_id: "checked_cop"
        device_class: "power_factor"
        state_class: "measurement"
        unit_of_measurement: ""
        availability: >
          {% set cop = states('sensor.heliotherm_heatpump_cop') | float(0) %}
          {{ ( (cop > 0) and (cop < 10) ) }}
        state: >
          {% set cop = states('sensor.heliotherm_heatpump_cop') | float %}
          {{ ( cop ) }}
```

Furthermore it handles the case where heliotherm_heatpump_cop is really unavailable via `float(0)`. I.e. it uses the default value 0 i.e. it makes the sensor unavailable.
