### DISCUSSION TITLE
adjusting the warm water temperatur via an automation

### DISCUSSION THREAD

**Discussion by karussell** [mbuchber/ha_heliotherm#48] [General]
Thanks a lot for this component. Works flawlessly!

Changing the water temperature via the provided widget works (using `+` and `-` and via the slider).

Now I'd like to change the water temperature via an automation. Is this possible?

Adjusting the temperature of the 'room target temperature' was possible via:

```yaml
action: climate.set_temperature
target:
  entity_id: climate.heliotherm_heatpump_raum_solltemperatur
data:
  temperature: 23
```

But just replacing the entity_id with `climate.heliotherm_heatpump_warmwasserbereitung` does not seem to work. It only changes the **measured** water temperature for a few seconds and then switches back to the previous temperature.

**Comment by karussell** [comment]
Ah, the trick is a different name and using two variables:

```yml
action: climate.set_temperature
target:
  entity_id: climate.heliotherm_heatpump_warmwasserbereitung
data:
  target_temp_low: 15
  target_temp_high: 50
```
